# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import emergency_pb2 as emergency__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in emergency_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmergencyAlertServiceStub(object):
    """Service principal de gestion des alertes d'urgence
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAlert = channel.unary_unary(
                '/emergency.EmergencyAlertService/CreateAlert',
                request_serializer=emergency__pb2.AlertRequest.SerializeToString,
                response_deserializer=emergency__pb2.AlertResponse.FromString,
                _registered_method=True)
        self.GetActiveAlerts = channel.unary_unary(
                '/emergency.EmergencyAlertService/GetActiveAlerts',
                request_serializer=emergency__pb2.ZoneRequest.SerializeToString,
                response_deserializer=emergency__pb2.AlertListResponse.FromString,
                _registered_method=True)
        self.UpdateAlertStatus = channel.unary_unary(
                '/emergency.EmergencyAlertService/UpdateAlertStatus',
                request_serializer=emergency__pb2.StatusUpdateRequest.SerializeToString,
                response_deserializer=emergency__pb2.AlertResponse.FromString,
                _registered_method=True)
        self.GetAlertHistory = channel.unary_unary(
                '/emergency.EmergencyAlertService/GetAlertHistory',
                request_serializer=emergency__pb2.HistoryRequest.SerializeToString,
                response_deserializer=emergency__pb2.AlertHistoryResponse.FromString,
                _registered_method=True)
        self.SubscribeAlerts = channel.unary_stream(
                '/emergency.EmergencyAlertService/SubscribeAlerts',
                request_serializer=emergency__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=emergency__pb2.AlertResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/emergency.EmergencyAlertService/HealthCheck',
                request_serializer=emergency__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=emergency__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class EmergencyAlertServiceServicer(object):
    """Service principal de gestion des alertes d'urgence
    """

    def CreateAlert(self, request, context):
        """Créer une nouvelle alerte
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveAlerts(self, request, context):
        """Récupérer les alertes actives d'une zone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAlertStatus(self, request, context):
        """Mettre à jour le statut d'une alerte
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlertHistory(self, request, context):
        """Consulter l'historique des alertes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeAlerts(self, request, context):
        """S'abonner aux alertes en temps réel (streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmergencyAlertServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAlert,
                    request_deserializer=emergency__pb2.AlertRequest.FromString,
                    response_serializer=emergency__pb2.AlertResponse.SerializeToString,
            ),
            'GetActiveAlerts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveAlerts,
                    request_deserializer=emergency__pb2.ZoneRequest.FromString,
                    response_serializer=emergency__pb2.AlertListResponse.SerializeToString,
            ),
            'UpdateAlertStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAlertStatus,
                    request_deserializer=emergency__pb2.StatusUpdateRequest.FromString,
                    response_serializer=emergency__pb2.AlertResponse.SerializeToString,
            ),
            'GetAlertHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlertHistory,
                    request_deserializer=emergency__pb2.HistoryRequest.FromString,
                    response_serializer=emergency__pb2.AlertHistoryResponse.SerializeToString,
            ),
            'SubscribeAlerts': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeAlerts,
                    request_deserializer=emergency__pb2.SubscribeRequest.FromString,
                    response_serializer=emergency__pb2.AlertResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=emergency__pb2.HealthCheckRequest.FromString,
                    response_serializer=emergency__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emergency.EmergencyAlertService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('emergency.EmergencyAlertService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmergencyAlertService(object):
    """Service principal de gestion des alertes d'urgence
    """

    @staticmethod
    def CreateAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emergency.EmergencyAlertService/CreateAlert',
            emergency__pb2.AlertRequest.SerializeToString,
            emergency__pb2.AlertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emergency.EmergencyAlertService/GetActiveAlerts',
            emergency__pb2.ZoneRequest.SerializeToString,
            emergency__pb2.AlertListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAlertStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emergency.EmergencyAlertService/UpdateAlertStatus',
            emergency__pb2.StatusUpdateRequest.SerializeToString,
            emergency__pb2.AlertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlertHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emergency.EmergencyAlertService/GetAlertHistory',
            emergency__pb2.HistoryRequest.SerializeToString,
            emergency__pb2.AlertHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/emergency.EmergencyAlertService/SubscribeAlerts',
            emergency__pb2.SubscribeRequest.SerializeToString,
            emergency__pb2.AlertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emergency.EmergencyAlertService/HealthCheck',
            emergency__pb2.HealthCheckRequest.SerializeToString,
            emergency__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
